#!/bin/sh

# command line version of the activator
# we have to create the same environment that it gets in the web app

#SCRIPT=$(readlink -f "$0")
#SCRIPTPATH=$(dirname "$SCRIPT")

# the command line code sets the logging configuration to
# a file name. It comes from the current diretory. So we have
# to cd to the right place. The web support code reads a config
# file from WEB-INF. That's the only real difference between the
# two contexts.

export XDG_CACHE_HOME="$HOME/$$"

trap 'rm -rf "$XDG_CACHE_HOME"' 2

cd /var/lib/activator

A=/var/www/tomcat/webapps/accounts
L="$A/WEB-INF/lib/*"
C="$A/WEB-INF/classes"

/etc/alternatives/java_sdk_11/bin/java -cp $C:"$L" Activator.User "$@"

rm -rf "$XDG_CACHE_HOME"
