reviewquotas: netapp.c postinmemory.c reviewquotas.c  parsesize.c
	gcc -g -o reviewquotas netapp.c postinmemory.c reviewquotas.c parsesize.c -ljansson -lcurl
parsesize: parsesize.c
	gcc -o parsesize -DMAIN parsesize.c

