.TH PAM_REG_CC 8
.SH NAME
pam_reg_cc \- register credential caches for renewd
.SH DESCRIPTION
.I  pam_reg_cc [usecollection] [usedefaultname]
.PP
Pam_reg_cc registers Kerberos credentials so that renewd will
renew them. Depending upon the configuration in /etc/krb5.conf,
it may also normalize the name to work around issues with various
versions of sshd.
.PP
Pam_reg_cc checks the current value of KRB5CCNAME in the environment that
PAM is preparing for the user process. If it is defined, 
pam_reg_cc registers the cache that was just created for
renewd to renew automatically.
.PP
pam_reg_cc implements both auth and session. Logically it should be
used in the auth stack after whatever module does Kerberos authentication.
However sshd sets up Kerberos credentially internally, and doesn't
call PAM's auth code. So the normal configuration is to put
it in session fairly near the beginning, before anything that
tries to access the user's home directory (particular on Ubuntu).
Auth will be used primarily when the
application doesn't call session, or when it doesn't have KRB5CCNAME
set for the session.
.PP
In case the application doesn't make KRB5CCNAME available, you can
set "usedefaultname." This will cause pam_reg_cc to assume that the
credential cache uses the default name as defined in /etc/krb5.conf.
This can be dangerous, since sshd and other applications may make their
own choice about the credential cache. But some applications need this.
.PP
KRB5CCNAME is sometimes set
to the default collection, rather than to the specific cache.
That can require pam_reg_cc to guess which cache was actually
just created. It will pick a cache from the collection that
has the user's main principal. That's the same cache that sssd
uses, so it should be the right one.
.PP
If usecollection is specified, and the cache is in a collection
type cache (e.g. KEYRING or KCM), strips
any subsidiary name. E.g if it is KEYRING:persistent:1003:1003,
although that name will be registered for renewd, the environment
variable will be updated to KEYRING:persistent:1003. This will 
allow kinit, klist, and kdestroy to work as intended with collections.
.PP
In general we recommend setting default_ccache_name in krb5.conf to
KEYRING:persistent:%{uid} or KCM:, and setting usecollection. 
.PP
Sshd has two known problems: (1) On Centos it tends to set KRB5CCNAME
to the actual cache name. If the user does kinit as a different
principal, it will overwrite the cache. This can cause the user to
lose access to NFS. To fix this, set the default cc in /etc/krb5.conf
to KEYRING:persistent:%{uid} or KCM:, and set "usecollection." As explained
above, that will fix up KRB5CCNAME to point to the collection. Kinit
is smart enough that it will create a new cache if the user kinits
as a different principal. If used with the gssd wrapper, gssd will
pick the right credential in the cache.
.PP
Sshd (2) On Ubuntu, it uses /tmp/krb5...., even if krb5.conf
sets the default credential cache to something else.
Because /tmp/krb5... isn't a collection, That causes the same
issue as above, but in addition, rpc.gssd doesn't seem to work as
well with credentials in /tmp as in KEYRING. So there's a special
check in pam_reg_cc. If the default in krb5.conf is a collection,
and KRB5CCNAME is something else, it copies the credentials into a new
collection that matches what's in krb5.conf and fixes up KRB5CCNAME to point to it. So on
Ubuntu we still recommend setting the default in krb5.conf to
KEYRING:persistent:%{uid} or KCM:, and setting "usecollection".
.PP
From auth, this module implements a no-op authenticate. The code is in setcred.
From session, it implements session start. Session end is a no-op. It does not 
make sense to use it for both auth and session, though it's normally harmless
.PP
If this module is being used in a system with renewd, you may want to warn users if the
credentials forwarded to them have too short a lifetime to be renewed. To warn if there
is less than 55 min left use. You may also want to specify ticket_warn_file, which is
a file with the text of the warning message to be printed. There's default text in case
it isn't specified, but this lets you specify your own.
.PP
.nf
[appdefaults]
register-cc = {
    ticket_minlife = 55m
    ticket_warn_file = /etc/krb5.ticketwarning
}
.fi
.PP
NOTE: There used to be additional functionality to make a second copy of the
credential cache. This turned out not to be useful, and has been removed.
