#!/usr/bin/perl
#
# Check that too-new features of Perl are not being used.
#
# This version of the check script supports mapping various directories to
# different version numbers.  This allows a newer version of Perl to be
# required for internal tools than for public code.
#
# The canonical version of this file is maintained in the rra-c-util package,
# which can be found at <https://www.eyrie.org/~eagle/software/rra-c-util/>.
#
# Written by Russ Allbery <eagle@eyrie.org>
# Copyright 2016 Russ Allbery <eagle@eyrie.org>
# Copyright 2012, 2013, 2014
#     The Board of Trustees of the Leland Stanford Junior University
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

use 5.006;
use strict;
use warnings;

use lib "$ENV{C_TAP_SOURCE}/tap/perl";

use Test::More;
use Test::RRA qw(skip_unless_automated use_prereq);
use Test::RRA::Automake qw(automake_setup perl_dirs);
use Test::RRA::Config qw($MINIMUM_VERSION %MINIMUM_VERSION);

# Skip for normal user installs since this doesn't affect functionality.
skip_unless_automated('Minimum version tests');

# Load prerequisite modules.
use_prereq('Test::MinimumVersion');

# Set up Automake testing.
automake_setup();

# For each exception case in %MINIMUM_VERSION, check the files that should
# have that minium version.  Sort for reproducible test order.  Also
# accumulate the list of directories we've already tested.
my @tested;
for my $version (sort keys %MINIMUM_VERSION) {
    my $paths_ref = $MINIMUM_VERSION{$version};
    all_minimum_version_ok($version, { paths => $paths_ref, no_plan => 1 });
    push(@tested, @{$paths_ref});
}

# Now, check anything that's left against the default minimum version.
my @paths = perl_dirs({ skip => [@tested] });
all_minimum_version_ok($MINIMUM_VERSION, { paths => \@paths, no_plan => 1 });

# Tell the TAP harness that we're done.
done_testing();
