#!/usr/bin/perl
#
# Check Perl scripts for strict, warnings, and syntax.
#
# Checks all Perl scripts in the tree for problems uncovered by Test::Strict.
# This includes using strict and warnings for every script and ensuring they
# all pass a syntax check.  Currently, test suite coverage is not checked.
#
# The canonical version of this file is maintained in the rra-c-util package,
# which can be found at <https://www.eyrie.org/~eagle/software/rra-c-util/>.
#
# Written by Russ Allbery <eagle@eyrie.org>
# Copyright 2016 Russ Allbery <eagle@eyrie.org>
# Copyright 2012, 2013, 2014
#     The Board of Trustees of the Leland Stanford Junior University
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

use 5.006;
use strict;
use warnings;

use lib "$ENV{C_TAP_SOURCE}/tap/perl";

use Test::More;
use Test::RRA qw(skip_unless_automated use_prereq);
use Test::RRA::Automake qw(automake_setup perl_dirs);
use Test::RRA::Config qw(@STRICT_IGNORE @STRICT_PREREQ);

# Skip for normal user installs since this doesn't affect functionality.
skip_unless_automated('Strictness tests');

# Load prerequisite modules.
use_prereq('Test::Strict', '0.25');

# Check whether all prerequisites are available, and skip the test if any of
# them are not.
for my $module (@STRICT_PREREQ) {
    use_prereq($module);
}

# Set up Automake testing.  This must be done after loading Test::Strict,
# since it wants to use FindBin to locate this script.
automake_setup();

# Run the actual tests.  We also want to check warnings.
$Test::Strict::TEST_WARNINGS = 1;
all_perl_files_ok(perl_dirs({ skip => [@STRICT_IGNORE] }));

# Suppress "used only once" warnings.
END { $Test::Strict::TEST_WARNINGS = 0 }
