.TH CREDSERV 8
.SH NAME
credserv \- provide Kerberos credentials from keytab stored to remote client
.SH SYNOPSIS
.B credserv
[ -d ]
.SH DESCRIPTION
.I  kgetcred
is designed for cron jobs or services that need access to Kerberos
credentials, but don't have an interactive user to supply them.
Kgetcred sends a request to a credserv server. The server looks
for a standard Kerberos keytab stores in a file of the form
/var/credserv/user-host.cs.rutgers.edu.keytab, where the username
is sent by kgetcred and the hostname is the host from which the
request comes. (The name is normalized by a DNS lookup.) If a keytab
exists and credentials can be built from it, they are returned to
kgetcred, which puts them into the user's default credential cache.
.PP
Normally the keytab must contain credentials for the specific user.
However for root, the principal is taken from the keytab itself.
The assumption is that root cronjobs will run with a principal
that has just those privileges needed for jobs on that host.
Obviously whatever process you use to store keytabs for this service
should make sure that root keytabs aren't set up by unauthorized people.
.PP
Credserv normally detaches from the terminal, and logs to syslog.
If -d is supplied it remains attached to the terminal, and prints
debug and error messasges there.
.PP
Kgetcred must authenticate itself to the server using the client's
host principal, from /etc/krb5.keytab. (To read it, kgetcred must
run setuid root. It drops privileges as soon as it has read that file.)
.PP
Credserv verifies that the hostname in the principal matches the IP
address from which the request came.
.PP
We assume that key tables are stored on the server in some separate 
process, e.g. a web application.
.PP
NOTE: You must make a service principal for credserv/HOST on the server
and add it to /etc/krb5.keytab.
.SH OPTIONS
.TP
.B \-d
do not detach, and print debugging messages
.SH "SEE ALSO"
kgetcred(1)

