#!/bin/sh

# show command to switch to the cache with a given principal

if test `id -u` = "0" -a -n "$SUDO_UID"
  then
    uid="$SUDO_UID"
    user="$SUDO_USER"
  else
    uid=`id -u`
    user=`id -nu`
fi

# normalize our default. klist will only work for KEYRING:persistent:uid.
# if it KEYRING:persistent:uid:foo, klist -l won't do anything.
#
if test -n "$KRB5CCNAME"
  then
  if expr "$KRB5CCNAME" : "KEYRING:persistent:$uid:" >/dev/null
    then KRB5CCNAME="KEYRING:persistent:$uid"
  fi
fi  

# normalize the argument
PRINC="$1"
# if it's missing, use the current user
if test -z "$PRINC"
  then
  PRINC="$user"
fi

# add the default domain if not supplied
if expr match "$PRINC" '.*@' > /dev/null
  then
     :
  else
    PRINC="$PRINC"@CS.RUTGERS.EDU
fi

# now get a list of the caches, and with grep select the right one
LINE=`klist -l | tail -2 | grep "$PRINC"`

if test -z "$LINE"
   then
   echo "Sorry, couldn't find a cache with that principal"
   exit 1
fi

# select just the cache name
NCACHE=`echo "$LINE" | sed -e 's/^.* //'`

echo To switch to this cache use
echo
if test "$SHELL" = "/bin/tcsh" -o "$SHELL" = "/bin/csh"
  then
    echo setenv KRB5CCNAME "$NCACHE"
  else
    echo KRB5CCNAME="$NCACHE"  
fi
echo


