all: kgetcred.c
	gcc -DHAVE_CONFIG_H  -I/usr/include/krb5 -I/usr/include/et  -DKRB5_DEPRECATED=1 -DKRB5_PRIVATE  -g -O2  -pthread -c kgetcred.c
	gcc  -Wl,--enable-new-dtags -Wl,-rpath -Wl,/usr/lib -g -O2  -o kgetcred kgetcred.o -lkrb5 -lk5crypto -lcom_err -lkrb5support  -lkeyutils -lresolv  -ldl
	cp kgetcred /usr/bin/kgetcred
	chmod u+s /usr/bin/kgetcred
