#!/bin/bash
rm -rf /usr/src/dhcp
mkdir -p /usr/src/dhcp
cd /usr/src/dhcp
# so rpmbuild goes here
export HOME=/usr/src/dhcp
# just in case. probaby done
yum install yum-utils rpm-build

yumdownloader --source dhcp
rpm -ivh ./dhcp-*rpm
yum-builddep dhcp

cp /staff/users/hedrick/dhcp-duplicate-hwaddr.patch rpmbuild/SOURCES/
# last patch number
if ! grep -q "dhcp-duplicate-hwaddr.patch" rpmbuild/SPECS/dhcp.spec ; then
  LASTP=`awk '/^Patch[0-9]*:/ {n = substr($1,6,length($1)-6) + 0; if (n > m) m = n; lastp = 1}END{print n}' rpmbuild/SPECS/dhcp.spec`
  THISP=$((LASTP+1))
  sed -i -e "/^Patch${LASTP}:/a Patch${THISP}: dhcp-duplicate-hwaddr.patch" -e "/^%patch${LASTP}/a %patch${THISP} -p1" rpmbuild/SPECS/dhcp.spec
fi
rpmbuild -bi rpmbuild/SPECS/dhcp.spec
install rpmbuild/BUILDROOT/dhcp-*/usr/sbin/dhcpd /usr/sbin/dhcpd -o root -g root -m 0755


