/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "rquota.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
rquotaproc_getquota_1(getquota_args arg1, getquota_rslt *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, RQUOTAPROC_GETQUOTA,
		(xdrproc_t) xdr_getquota_args, (caddr_t) &arg1,
		(xdrproc_t) xdr_getquota_rslt, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rquotaproc_getactivequota_1(getquota_args arg1, getquota_rslt *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, RQUOTAPROC_GETACTIVEQUOTA,
		(xdrproc_t) xdr_getquota_args, (caddr_t) &arg1,
		(xdrproc_t) xdr_getquota_rslt, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rquotaproc_setquota_1(setquota_args arg1, setquota_rslt *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, RQUOTAPROC_SETQUOTA,
		(xdrproc_t) xdr_setquota_args, (caddr_t) &arg1,
		(xdrproc_t) xdr_setquota_rslt, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rquotaproc_setactivequota_1(setquota_args arg1, setquota_rslt *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, RQUOTAPROC_SETACTIVEQUOTA,
		(xdrproc_t) xdr_setquota_args, (caddr_t) &arg1,
		(xdrproc_t) xdr_setquota_rslt, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rquotaproc_getquota_2(ext_getquota_args arg1, getquota_rslt *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, RQUOTAPROC_GETQUOTA,
		(xdrproc_t) xdr_ext_getquota_args, (caddr_t) &arg1,
		(xdrproc_t) xdr_getquota_rslt, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rquotaproc_getactivequota_2(ext_getquota_args arg1, getquota_rslt *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, RQUOTAPROC_GETACTIVEQUOTA,
		(xdrproc_t) xdr_ext_getquota_args, (caddr_t) &arg1,
		(xdrproc_t) xdr_getquota_rslt, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rquotaproc_setquota_2(ext_setquota_args arg1, setquota_rslt *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, RQUOTAPROC_SETQUOTA,
		(xdrproc_t) xdr_ext_setquota_args, (caddr_t) &arg1,
		(xdrproc_t) xdr_setquota_rslt, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rquotaproc_setactivequota_2(ext_setquota_args arg1, setquota_rslt *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, RQUOTAPROC_SETACTIVEQUOTA,
		(xdrproc_t) xdr_ext_setquota_args, (caddr_t) &arg1,
		(xdrproc_t) xdr_setquota_rslt, (caddr_t) clnt_res,
		TIMEOUT));
}
