/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rquota.h"


void
rquotaprog_1(char *host)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	getquota_rslt result_1;
	getquota_args rquotaproc_getquota_1_arg1;
	enum clnt_stat retval_2;
	getquota_rslt result_2;
	getquota_args rquotaproc_getactivequota_1_arg1;
	enum clnt_stat retval_3;
	setquota_rslt result_3;
	setquota_args rquotaproc_setquota_1_arg1;
	enum clnt_stat retval_4;
	setquota_rslt result_4;
	setquota_args rquotaproc_setactivequota_1_arg1;

#ifndef	DEBUG
	clnt = clnt_create (host, RQUOTAPROG, RQUOTAVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	retval_1 = rquotaproc_getquota_1(rquotaproc_getquota_1_arg1, &result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_2 = rquotaproc_getactivequota_1(rquotaproc_getactivequota_1_arg1, &result_2, clnt);
	if (retval_2 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_3 = rquotaproc_setquota_1(rquotaproc_setquota_1_arg1, &result_3, clnt);
	if (retval_3 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_4 = rquotaproc_setactivequota_1(rquotaproc_setactivequota_1_arg1, &result_4, clnt);
	if (retval_4 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
rquotaprog_2(char *host)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	getquota_rslt result_1;
	ext_getquota_args rquotaproc_getquota_2_arg1;
	enum clnt_stat retval_2;
	getquota_rslt result_2;
	ext_getquota_args rquotaproc_getactivequota_2_arg1;
	enum clnt_stat retval_3;
	setquota_rslt result_3;
	ext_setquota_args rquotaproc_setquota_2_arg1;
	enum clnt_stat retval_4;
	setquota_rslt result_4;
	ext_setquota_args rquotaproc_setactivequota_2_arg1;

#ifndef	DEBUG
	clnt = clnt_create (host, RQUOTAPROG, EXT_RQUOTAVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	retval_1 = rquotaproc_getquota_2(rquotaproc_getquota_2_arg1, &result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_2 = rquotaproc_getactivequota_2(rquotaproc_getactivequota_2_arg1, &result_2, clnt);
	if (retval_2 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_3 = rquotaproc_setquota_2(rquotaproc_setquota_2_arg1, &result_3, clnt);
	if (retval_3 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_4 = rquotaproc_setactivequota_2(rquotaproc_setactivequota_2_arg1, &result_4, clnt);
	if (retval_4 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	rquotaprog_1 (host);
	rquotaprog_2 (host);
exit (0);
}
