/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rquota.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <errno.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

// Rutgers start

#include <arpa/inet.h> // For ntohs()
#include <netdb.h>

char nfs_pseudoroot[PATH_MAX];

#define NFSD_XTAB_PATH "/var/lib/nfs/etab"
#define QPORT 875

/* Parse NFSD export table and find a filesystem pseudoroot if it is there */
static void get_pseudoroot(void)
{
	FILE *f;
	char exp_line[PATH_MAX];
	char *c;

	// default if we don't find anything
	strcpy(nfs_pseudoroot, "/");

	if (!(f = fopen(NFSD_XTAB_PATH, "r"))) {
	  printf("Warning: Cannot open export table %s: %s\nUsing '/' as a pseudofilesystem root.\n", NFSD_XTAB_PATH, strerror(errno));
		return;
	}

	while (fgets(exp_line, sizeof(exp_line), f)) {
		if (exp_line[0] == '#' || exp_line[0] == '\n')	/* Comment, empty line? */
			continue;
		c = strchr(exp_line, '\t');
		if (!c)	/* Huh, line we don't understand... */
			continue;
		*c = '\0';
		/* Find the beginning of export options */
		c = strchr(c+1, '(');
		if (!c)
			continue;
		c = strstr(c, "fsid=0");
		if (c) {
			strlcpy(nfs_pseudoroot, exp_line, PATH_MAX);
			strlcat(nfs_pseudoroot, "/", PATH_MAX);
			break;
		}
	}
	fclose(f);
}

int
makesocket(int istcp) {
  struct servent *service;
  struct sockaddr_in6 sin6;
  int optval = 1;
  int sock;

  sock = socket(AF_INET6, (istcp ? SOCK_STREAM : SOCK_DGRAM), 0);
  if (!sock)
    {fprintf(stderr, "socket failed\n"); exit(1);}

  setsockopt(sock, SOL_SOCKET, SO_REUSEADDR, &optval, sizeof(optval));

  bzero(&sin6, sizeof(sin6));
  sin6.sin6_family = AF_INET6;
  inet_pton(AF_INET6, "::", &sin6.sin6_addr);
  service = getservbyname("rquotad", (istcp ? "tcp" : "udp"));
  if (service)
    sin6.sin6_port = service->s_port;
  else
    sin6.sin6_port = htons(QPORT);

  if (bind(sock, (const struct sockaddr *)&sin6, sizeof(sin6)) != 0)
    {fprintf(stderr, "bind failed\n"); exit(1);}
	
  if (istcp) {
    if (listen(sock, SOMAXCONN) != 0)
      {fprintf(stderr, "listen failed"); exit(1);}
  }

  return sock;
}
  

// Rutgers end

int
_rquotaproc_getquota_1 (getquota_args  *argp, void *result, struct svc_req *rqstp)
{
	return (rquotaproc_getquota_1_svc(*argp, result, rqstp));
}

int
_rquotaproc_getactivequota_1 (getquota_args  *argp, void *result, struct svc_req *rqstp)
{
	return (rquotaproc_getactivequota_1_svc(*argp, result, rqstp));
}

int
_rquotaproc_setquota_1 (setquota_args  *argp, void *result, struct svc_req *rqstp)
{
	return (rquotaproc_setquota_1_svc(*argp, result, rqstp));
}

int
_rquotaproc_setactivequota_1 (setquota_args  *argp, void *result, struct svc_req *rqstp)
{
	return (rquotaproc_setactivequota_1_svc(*argp, result, rqstp));
}

int
_rquotaproc_getquota_2 (ext_getquota_args  *argp, void *result, struct svc_req *rqstp)
{
	return (rquotaproc_getquota_2_svc(*argp, result, rqstp));
}

int
_rquotaproc_getactivequota_2 (ext_getquota_args  *argp, void *result, struct svc_req *rqstp)
{
	return (rquotaproc_getactivequota_2_svc(*argp, result, rqstp));
}

int
_rquotaproc_setquota_2 (ext_setquota_args  *argp, void *result, struct svc_req *rqstp)
{
	return (rquotaproc_setquota_2_svc(*argp, result, rqstp));
}

int
_rquotaproc_setactivequota_2 (ext_setquota_args  *argp, void *result, struct svc_req *rqstp)
{
	return (rquotaproc_setactivequota_2_svc(*argp, result, rqstp));
}

static void
rquotaprog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		getquota_args rquotaproc_getquota_1_arg;
		getquota_args rquotaproc_getactivequota_1_arg;
		setquota_args rquotaproc_setquota_1_arg;
		setquota_args rquotaproc_setactivequota_1_arg;
	} argument;
	union {
		getquota_rslt rquotaproc_getquota_1_res;
		getquota_rslt rquotaproc_getactivequota_1_res;
		setquota_rslt rquotaproc_setquota_1_res;
		setquota_rslt rquotaproc_setactivequota_1_res;
	} result;
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case RQUOTAPROC_GETQUOTA:
		_xdr_argument = (xdrproc_t) xdr_getquota_args;
		_xdr_result = (xdrproc_t) xdr_getquota_rslt;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rquotaproc_getquota_1;
		break;

	case RQUOTAPROC_GETACTIVEQUOTA:
		_xdr_argument = (xdrproc_t) xdr_getquota_args;
		_xdr_result = (xdrproc_t) xdr_getquota_rslt;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rquotaproc_getactivequota_1;
		break;

	case RQUOTAPROC_SETQUOTA:
		_xdr_argument = (xdrproc_t) xdr_setquota_args;
		_xdr_result = (xdrproc_t) xdr_setquota_rslt;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rquotaproc_setquota_1;
		break;

	case RQUOTAPROC_SETACTIVEQUOTA:
		_xdr_argument = (xdrproc_t) xdr_setquota_args;
		_xdr_result = (xdrproc_t) xdr_setquota_rslt;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rquotaproc_setactivequota_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
	if (retval > 0 && !svc_sendreply(transp, (xdrproc_t) _xdr_result, (char *)&result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	if (!rquotaprog_1_freeresult (transp, _xdr_result, (caddr_t) &result))
		fprintf (stderr, "%s", "unable to free results");

	return;
}

static void
rquotaprog_2(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		ext_getquota_args rquotaproc_getquota_2_arg;
		ext_getquota_args rquotaproc_getactivequota_2_arg;
		ext_setquota_args rquotaproc_setquota_2_arg;
		ext_setquota_args rquotaproc_setactivequota_2_arg;
	} argument;
	union {
		getquota_rslt rquotaproc_getquota_2_res;
		getquota_rslt rquotaproc_getactivequota_2_res;
		setquota_rslt rquotaproc_setquota_2_res;
		setquota_rslt rquotaproc_setactivequota_2_res;
	} result;
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case RQUOTAPROC_GETQUOTA:
		_xdr_argument = (xdrproc_t) xdr_ext_getquota_args;
		_xdr_result = (xdrproc_t) xdr_getquota_rslt;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rquotaproc_getquota_2;
		break;

	case RQUOTAPROC_GETACTIVEQUOTA:
		_xdr_argument = (xdrproc_t) xdr_ext_getquota_args;
		_xdr_result = (xdrproc_t) xdr_getquota_rslt;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rquotaproc_getactivequota_2;
		break;

	case RQUOTAPROC_SETQUOTA:
		_xdr_argument = (xdrproc_t) xdr_ext_setquota_args;
		_xdr_result = (xdrproc_t) xdr_setquota_rslt;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rquotaproc_setquota_2;
		break;

	case RQUOTAPROC_SETACTIVEQUOTA:
		_xdr_argument = (xdrproc_t) xdr_ext_setquota_args;
		_xdr_result = (xdrproc_t) xdr_setquota_rslt;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rquotaproc_setactivequota_2;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
	if (retval > 0 && !svc_sendreply(transp, (xdrproc_t) _xdr_result, (char *)&result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	if (!rquotaprog_2_freeresult (transp, _xdr_result, (caddr_t) &result))
		fprintf (stderr, "%s", "unable to free results");

	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	// Rutgers
	get_pseudoroot();

	pmap_unset (RQUOTAPROG, RQUOTAVERS);
	pmap_unset (RQUOTAPROG, EXT_RQUOTAVERS);

	// Rutgers
	transp = svcudp_create(makesocket(0));
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, RQUOTAPROG, RQUOTAVERS, rquotaprog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (RQUOTAPROG, RQUOTAVERS, udp).");
		exit(1);
	}
	if (!svc_register(transp, RQUOTAPROG, EXT_RQUOTAVERS, rquotaprog_2, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (RQUOTAPROG, EXT_RQUOTAVERS, udp).");
		exit(1);
	}

	// Rutgers
	transp = svctcp_create(makesocket(1), 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, RQUOTAPROG, RQUOTAVERS, rquotaprog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (RQUOTAPROG, RQUOTAVERS, tcp).");
		exit(1);
	}
	if (!svc_register(transp, RQUOTAPROG, EXT_RQUOTAVERS, rquotaprog_2, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (RQUOTAPROG, EXT_RQUOTAVERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
